// Regenerate src/guides.js (the optional par ghost) from the bot's par tapes.
//   node tools/guides.mjs
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { ROOMS } from "../src/rooms.js";

const guides = {};
for (const room of ROOMS) {
  const file = `tests/par/${room.id}.json`;
  if (existsSync(file)) guides[room.id] = JSON.parse(readFileSync(file, "utf8"));
}
writeFileSync(
  "src/guides.js",
  "// Generated by tools/guides.mjs from tests/par. Do not edit by hand.\n" +
    `export const GUIDES = ${JSON.stringify(guides)};\n`,
);
console.log(`${Object.keys(guides).length} guides written`);
