import * as THREE from '../vendor/three.module.js';
import {paintTexture,storyTexture} from './art.js';
const smooth=(a,b,t)=>{const v=THREE.MathUtils.clamp((t-a)/(b-a),0,1);return v*v*(3-2*v);};
export class Cinematics{
 constructor(host,settings,audio){this.host=host;this.settings=settings;this.audio=audio;this.active=false;this.resources=[];}
 mesh(geo,mat,parent=this.scene){const m=new THREE.Mesh(geo,mat);parent.add(m);m.castShadow=!mat.transparent&&this.settings.world!=='low';m.receiveShadow=true;this.resources.push(geo);return m;}
 box(x,y,z,w,h,d,mat,parent){const m=this.mesh(new THREE.BoxGeometry(w,h,d),mat,parent);m.position.set(x,y,z);return m;}
 material(color,opts={}){const m=new (opts.transmission!==undefined?THREE.MeshPhysicalMaterial:THREE.MeshStandardMaterial)({color,roughness:.75,...opts});this.resources.push(m);return m;}
 start(kind,done,marks=[],act=0){this.stop();this.active=true;this.kind=kind;this.duration=kind==='opening'?6:kind==='ending'?40:kind==='escape'?8:kind==='farmhouse'?5:4;this.time=0;this.fromAct=act;this.done=done;this.fired=new Set();this.scene=new THREE.Scene();this.scene.background=new THREE.Color(kind==='ending'?0x88795d:0x080f16);this.scene.fog=new THREE.Fog(this.scene.background,18,70);this.camera=new THREE.PerspectiveCamera(36,1,.1,150);this.key=new THREE.DirectionalLight(kind==='ending'?0xffe3af:0xc8d7e5,kind==='ending'?2.8:1.2);this.key.position.set(-4,8,7);this.key.castShadow=this.settings.world!=='low';this.key.shadow.mapSize.set(1024,1024);this.resources.push(this.key.shadow);this.key.shadow.camera.left=-12;this.key.shadow.camera.right=12;this.key.shadow.camera.top=12;this.key.shadow.camera.bottom=-12;this.key.shadow.bias=-.0004;this.key.shadow.normalBias=.025;this.key.shadow.radius=2;this.ambient=new THREE.HemisphereLight(0xcbd5d2,0x232524,kind==='ending'?1:kind==='opening'?.35:.9);this.scene.add(this.key,this.ambient);this.glow=new THREE.PointLight(0x7ff0d8,12,9);this.glow.position.set(0,1,2);this.scene.add(this.glow);
 const steel=this.material(0x46535d,{metalness:.65,roughness:.35}),wood=this.material(0xb28a5d,{map:paintTexture('wood')}),cloth=this.material(0xe7dec2,{map:paintTexture('cloth')});this.resources.push(wood.map,cloth.map);const floor=this.material(kind==='ending'?0x94714e:0x353d43,{map:paintTexture('concrete')});this.resources.push(floor.map);this.box(0,-1.15,0,70,.25,50,floor);this.box(0,-.12,0,kind==='opening'?3.4:10,.25,5,kind==='ending'?wood:steel);for(const x of[-4.4,4.4])this.box(x,-.6,-1,.15,1,1,kind==='ending'?wood:steel);if(kind==='ending'){this.box(0,.023,.1,8,.025,3.4,cloth);this.box(0,4,-5,30,10,.3,this.material(0xb4a281));const frame=this.material(0x675139);for(const x of[-4,-1])this.box(x,3,-4.7,.12,4,.2,frame);for(const y of[1,3,5])this.box(-2.5,y,-4.7,3,.12,.2,frame);this.box(-2.5,3,-4.9,3,4,.1,this.material(0xffedc8,{emissive:0xffdda0,emissiveIntensity:.8}));for(let i=0;i<3;i++){const beam=this.box(-1+i*.7,1.8,1,1.2,5,.015,this.material(0xffe1a2,{transparent:true,opacity:.055,depthWrite:false}));beam.rotation.z=-.7;}}
 else if(kind==='opening'){for(let x=-9;x<10;x+=3){this.box(x,4,-5,.2,12,.4,steel);this.box(x,3,-4.8,2.8,.15,.4,steel);}this.box(0,2.8,-6,24,9,.4,this.material(0x17222d));}
 this.jar=new THREE.Group();this.scene.add(this.jar);const glass=this.material(0xd1e8dc,{transparent:true,opacity:.25,roughness:.08,metalness:.05,side:THREE.DoubleSide,depthWrite:false});this.glass=this.mesh(new THREE.CylinderGeometry(.72,.8,1.9,48,1,true),glass,this.jar);this.glass.position.y=1;const rim=this.material(0xb4c8bc,{metalness:.4,roughness:.2});for(const y of[.08,1.94]){const ring=this.mesh(new THREE.TorusGeometry(y<1?.78:.72,.035,8,48),rim,this.jar);ring.rotation.x=Math.PI/2;ring.position.y=y;}this.lid=this.mesh(new THREE.CylinderGeometry(.83,.83,.14,48),this.material(0xb1955f,{metalness:.4,roughness:.32}),this.jar);this.lid.position.y=2.04;
 const labelMap=storyTexture('label');this.resources.push(labelMap);this.label=this.mesh(new THREE.PlaneGeometry(1.04,.76),new THREE.MeshBasicMaterial({map:labelMap}),this.jar);this.resources.push(this.label.material);this.label.position.set(0,kind==='opening'?.7:1,.81);
 this.pip=new THREE.Group();this.scene.add(this.pip);const pts=[new THREE.Vector2(0,0)];for(let i=0;i<=28;i++){const a=i/28*Math.PI/2;pts.push(new THREE.Vector2(.49*Math.cos(a),.8*Math.sin(a)));}this.gel=this.material(0x2bc4a8,{emissive:0x0e6b5c,emissiveIntensity:.24,roughness:.1,metalness:0,transmission:.45,thickness:.55,ior:1.35,clearcoat:1});this.mesh(new THREE.LatheGeometry(pts,40),this.gel,this.pip);this.eyes=[];for(const x of[-.14,.14]){const eye=this.mesh(new THREE.SphereGeometry(.05,16,12),this.material(0x1b2a26),this.pip);eye.position.set(x,.44,.42);eye.scale.set(1,1.55,.45);this.eyes.push(eye);}this.fill=this.mesh(new THREE.CylinderGeometry(.67,.73,1,40),this.gel,this.jar);this.fill.position.y=.15;this.fill.scale.y=.08;this.fill.visible=kind==='ending';this.surface=this.mesh(new THREE.SphereGeometry(1,32,16),this.gel,this.jar);this.surface.scale.set(.68,.04,.68);this.surface.visible=kind==='ending';this.stream=this.mesh(new THREE.CylinderGeometry(.09,.17,1,16),this.gel);this.stream.visible=false;this.drip=this.mesh(new THREE.SphereGeometry(.055,12,8),this.gel);this.drip.visible=kind==='opening';
 const crackGeo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(.12,1.9,.76),new THREE.Vector3(-.03,1.56,.8),new THREE.Vector3(.19,1.36,.8),new THREE.Vector3(.02,.95,.8),new THREE.Vector3(.13,.61,.79)]);this.crack=new THREE.Line(crackGeo,new THREE.LineBasicMaterial({color:0xe5f8ee,transparent:true}));this.resources.push(crackGeo,this.crack.material);this.jar.add(this.crack);this.crack.visible=false;
 this.map=new THREE.Group();this.scene.add(this.map);this.map.visible=false;const wall=this.material(0x283237),lit=this.material(0xd2ba86,{emissive:0x957f56,emissiveIntensity:.5}),death=this.material(0x7ff0d8,{emissive:0x2bc4a8,emissiveIntensity:1});for(let i=0;i<9;i++){this.box(0,i*1.15-8,-9,8,.96,.5,wall,this.map);for(let x=-3;x<=3;x++)this.box(x,i*1.15-8,-8.7,.42,.34,.02,lit,this.map);}const marksGeo=new THREE.SphereGeometry(.035,6,4);this.resources.push(marksGeo);const markMeshes=new THREE.InstancedMesh(marksGeo,death,Math.min(marks.length,5000));const tr=new THREE.Object3D();marks.slice(0,5000).forEach((m,i)=>{const act=Number(m.room.split('.')[1]);tr.position.set(-3.5+(m.x%32)/32*7,act*1.15-8+(m.y%18)/18*.8,-8.64);tr.updateMatrix();markMeshes.setMatrixAt(i,tr.matrix);});this.map.add(markMeshes);this.resources.push(markMeshes);this.travel=this.box(-3,-7.9,-8.5,.48,.38,.05,this.gel,this.map);
 this.photo=this.mesh(new THREE.PlaneGeometry(3,2.25),this.material(0xffffff,{map:storyTexture('photo')}));this.resources.push(this.photo.material.map);this.photo.position.set(3.4,1.2,-2);this.photo.rotation.y=-.15;this.farm=new THREE.Group();this.scene.add(this.farm);this.farm.visible=false;this.box(0,1,-7,6,3,2,this.material(0xa98b67),this.farm);const roofGeo=new THREE.BufferGeometry();roofGeo.setAttribute('position',new THREE.Float32BufferAttribute([-3.4,2.5,-8.2,3.4,2.5,-8.2,0,4.2,-8.2,-3.4,2.5,-5.8,3.4,2.5,-5.8,0,4.2,-5.8],3));roofGeo.setIndex([0,3,2,3,5,2,1,2,4,4,2,5]);roofGeo.computeVertexNormals();this.mesh(roofGeo,this.material(0x464a43,{side:THREE.DoubleSide}),this.farm);const gable=new THREE.BufferGeometry();gable.setAttribute('position',new THREE.Float32BufferAttribute([-3.4,2.5,-5.82,3.4,2.5,-5.82,0,4.2,-5.82],3));gable.computeVertexNormals();this.mesh(gable,this.material(0xa98b67),this.farm);const siding=this.material(0xbfa47a,{map:wood.map}),trim=this.material(0xd9cfb7);for(let i=0;i<13;i++)this.box(0,-.38+i*.23,-5.97,5.96,.215,.035,siding,this.farm);for(const x of[-3,3])this.box(x,1,-5.88,.1,3,.1,trim,this.farm);for(const x of[.16,1.24])this.box(x,1.6,-5.86,.085,1.25,.1,trim,this.farm);for(const y of[.99,2.21])this.box(.7,y,-5.86,1.16,.085,.1,trim,this.farm);this.box(.7,1.6,-5.82,.05,1.2,.06,trim,this.farm);this.box(.7,1.6,-5.82,1.1,.05,.06,trim,this.farm);for(const x of[-1.75,-.65])this.box(x,.45,-5.8,.09,2.1,.1,trim,this.farm);this.box(-1.2,1.5,-5.8,1.2,.09,.1,trim,this.farm);this.box(-1.2,-.48,-5.3,1.5,.16,1,wood,this.farm);this.box(.7,1.6,-5.95,.9,1.1,.03,this.material(0xffdfa4,{emissive:0xffb953,emissiveIntensity:1.5}),this.farm);this.box(-1.2,.5,-5.9,1,2,.03,this.material(0x4a3d2d),this.farm);
 this.hatch=this.box(0,3,-1,5,.25,3,steel);this.hatch.visible=false;this.field=new THREE.Group();this.scene.add(this.field);for(let i=0;i<4;i++){const hill=this.mesh(new THREE.SphereGeometry(1,24,12),this.material(i%2?0x68664e:0x4d584f),this.field);hill.position.set(-9+i*6,-2.5,-10-i*2);hill.scale.set(9,2,4);}const earth=this.box(0,-.9,-6,70,.25,45,this.material(0x777159,{map:floor.map}),this.field);this.box(-1.2,-.758,1,1.8,.012,14,this.material(0xb7a47c),this.field);for(let i=0;i<12;i++){const x=-11+i*2;this.box(x,0,-12,.1,1.6,.1,wood,this.field);this.box(x+.9,.4,-12,1.9,.08,.08,wood,this.field);this.box(x+.9,-.1,-12,1.9,.08,.08,wood,this.field);}for(const x of[-12,-9,10,13]){this.box(x,1,-17,.3,4,.3,wood,this.field);const tree=this.mesh(new THREE.SphereGeometry(1,16,12),this.material(0x424d45),this.field);tree.position.set(x,3.4,-17);tree.scale.set(2.3,2.8,1.4);}const skyMat=new THREE.ShaderMaterial({uniforms:{top:{value:new THREE.Color(kind==='farmhouse'?0x85999b:0x142434)},bottom:{value:new THREE.Color(kind==='farmhouse'?0xe8cfa4:0x435362)}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'varying vec2 vUv;uniform vec3 top;uniform vec3 bottom;void main(){gl_FragColor=vec4(mix(bottom,top,smoothstep(.1,.8,vUv.y)),1.0);}',depthWrite:false});this.resources.push(skyMat);this.box(0,9,-35,100,35,.01,skyMat,this.field);if(kind==='farmhouse'){const sunMat=new THREE.MeshBasicMaterial({color:0xffe1aa,fog:false});this.resources.push(sunMat);const sun=this.mesh(new THREE.SphereGeometry(.65,24,16),sunMat,this.field);sun.position.set(-11,6,-32);}this.windowLight=new THREE.PointLight(0xffd393,5,7,2);this.windowLight.position.set(.7,1.6,-4.8);this.field.add(this.windowLight);const rainGeo=new THREE.BufferGeometry(),rainVertices=[];for(let i=0;i<100;i++){const x=(i*47%193)/193*24-12,y=(i*73%191)/191*10;rainVertices.push(x,y,-3,x-.14,y-.5,-3);}rainGeo.setAttribute('position',new THREE.Float32BufferAttribute(rainVertices,3));this.rain=new THREE.LineSegments(rainGeo,new THREE.LineBasicMaterial({color:0xb5c4d3,transparent:true,opacity:.24}));this.resources.push(rainGeo,this.rain.material);this.field.add(this.rain);this.field.visible=kind==='escape'||kind==='farmhouse';this.rain.visible=kind==='escape';if(kind==='lift'||kind==='escape'||kind==='farmhouse'){for(const c of this.scene.children)if(!c.isLight&&c!==this.map&&c!==this.farm&&c!==this.field&&c!==this.hatch)c.visible=false;}this.fade=1;}

 cue(id,at){if(this.time>=at&&!this.fired.has(id)){this.fired.add(id);this.audio.event(id);}}
 finish(){if(!this.active)return;const done=this.done;this.stop();done?.();}
 stop(){this.active=false;for(const r of this.resources)r.dispose?.();this.resources=[];}
 update(dt){if(!this.active)return;this.time+=dt;const t=this.time,kind=this.kind;this.fade=1;this.jar.visible=kind==='opening'||kind==='ending';this.pip.visible=this.jar.visible||kind==='escape';this.photo.visible=kind==='opening';this.map.visible=kind==='lift';this.camera.aspect=(this.host.canvas.clientWidth||innerWidth)/(this.host.canvas.clientHeight||innerHeight);this.camera.updateProjectionMatrix();
 if(kind==='opening'){const push=smooth(0,2.3,t);this.camera.position.set(2.6-push*1.4,1.7,9-push*3);this.camera.lookAt(0,.9,0);this.fade=smooth(0,.7,t)*(1-smooth(5.7,6,t));this.drip.position.set(.08,5-smooth(1.8,2.6,t)*3,0);this.drip.visible=t<2.6;this.crack.visible=t>=2.6;this.cue('cinema.crack',2.6);const out=smooth(3.1,4.8,t);this.glass.material.opacity=.25*(1-out);this.lid.position.y=2.04+out*.18;this.lid.rotation.z=out*.3;this.pip.position.set(out*2.2,.75*(1-out)-smooth(4.1,4.8,t)*1.025,out*.5);this.pip.scale.set(1+Math.sin(out*Math.PI)*.4,1-Math.sin(out*Math.PI)*.5,1);this.cue('cinema.spill',3.4);this.eyes.forEach(e=>e.scale.y=t<4.6?.05:1.55);}
 if(kind==='ending'){this.photo.visible=false;this.lid.position.y=3.1;const pour=smooth(6,15,t),settle=smooth(16,19,t);this.pip.position.set(-.78+pour*.72,1.95-pour*.15,.08);this.pip.scale.set(1-pour*.96,1-pour*.65,1-pour*.96);this.pip.visible=t<16;this.fill.scale.y=.08+pour*1.48;this.fill.position.y=.1+this.fill.scale.y/2;this.surface.position.y=.1+this.fill.scale.y+Math.sin(t*2)*.007;this.stream.visible=t>6&&t<15;this.stream.position.set(-.15,1.45,0);this.stream.scale.set(1,1.2,1);this.lid.position.y=3.1-settle*1.06;this.cue('cinema.pour',6);this.cue('cinema.lid',18.8);this.cue('cinema.home',20);const close=smooth(20,26,t),pull=smooth(31,38,t);this.camera.position.set(2.5*(1-close)+pull*3.5,2.6-close*1.35+pull*3.5,8-close*4+pull*13);this.camera.lookAt(0,1,0);this.fade=smooth(0,1.5,t)*(1-smooth(38,40,t));this.glow.intensity=8+pour*8;}
 if(kind==='lift'){this.camera.position.set(0,-3,14);this.camera.lookAt(0,-3,-9);this.travel.position.y=this.fromAct*1.15-8+smooth(.5,3.5,t)*1.15;this.fade=smooth(0,.5,t)*(1-smooth(3.5,4,t));this.cue('cinema.lift',.2);}
 if(kind==='escape'||kind==='farmhouse'){this.photo.visible=false;this.hatch.visible=kind==='escape';this.farm.visible=true;this.scene.background.setHex(kind==='escape'?0x1b2837:0x9b8d70);this.key.color.setHex(kind==='escape'?0xbacbdd:0xffdb9f);this.key.intensity=kind==='escape'?1.4:3.5;this.glow.intensity=kind==='escape'?12:0;this.hatch.position.x=smooth(0,3,t)*5;this.hatch.position.y=-.6;if(kind==='escape'){this.pip.position.set(smooth(3,7,t)*2.8,-1.9+smooth(1.5,4,t)*1.125,0);this.pip.scale.setScalar(1);}this.rain.position.y=-(t*3%2);this.rain.visible=kind==='escape'&&this.settings.motion!==false;this.camera.position.set(4-smooth(0,this.duration,t)*3,1+smooth(0,this.duration,t)*3,14);this.camera.lookAt(0,1,-7);this.fade=smooth(0,.7,t)*(1-smooth(this.duration-1,this.duration,t));this.cue(kind==='escape'?'cinema.hatch':'cinema.dawn',.3);}
 if(this.settings.motion===false){this.camera.position.set(kind==='ending'?1.2:0,2,8);this.camera.lookAt(0,1,0);}this.host.renderer.render(this.scene,this.camera);if(t>=this.duration)this.finish();return this.fade;}
}
